apiVersion: v1
kind: ReplicationController
metadata:
  name: aggremod-7
  labels:
    name: aggremod
    version: "7"
spec:
  replicas: 1
  selector:
    name: aggremod
    version: "7"
  template:
    metadata:
      labels:
        name: aggremod
        version: "7"
    spec:
      containers:
        - name: aggremod
          image: asia.gcr.io/ianlewis-org/aggremod:0.9
          livenessProbe:
            # an http probe
            httpGet:
              path: /_status/healthz
              port: 8080
            # length of time to wait for a pod to initialize
            # after pod startup, before applying health checking
            initialDelaySeconds: 30
            timeoutSeconds: 1
          volumeMounts:
            - name: secret-volume
              mountPath: /secrets
            - name: certs
              mountPath: /etc/ssl/certs
              readOnly: true
          resources:
            limits:
              memory: 15Mi
              cpu: 10m
        - name: fluentd
          image: asia.gcr.io/ianlewis-org/aggremod-fluentd:latest-2
          env:
            - name: GCP_SERVICE_ACCOUNT_EMAIL
              value: 2327118307-g1trnquhoguc6ier2bpt8u7ev3tkkuj8@developer.gserviceaccount.com
            - name: GCP_PROJECT
              value: ianlewis-org
            - name: GCP_BIGQUERY_DATASET
              value: homesensors
            - name: GCP_BIGQUERY_TABLE
              value: sensordata
          ports:
            - containerPort: 24224
          volumeMounts:
            - name: certs
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: secret-volume
              mountPath: /secrets
            - name: fluentd-file-buffer
              mountPath: /var/log/fluent/
          resources:
            limits:
              memory: 100Mi
              cpu: 10m
      volumes: 
        - name: certs
          hostPath:
            path: /etc/ssl/certs
        - name: secret-volume
          secret:
            secretName: aggremod-secret
        - name: fluentd-file-buffer
          gcePersistentDisk:
            # This GCE PD must already exist.
            pdName: aggremod-fluentd-buffer
            fsType: ext4
