apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aggremod
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: aggremod
    spec:
      containers:
        - name: aggremod
          image: asia.gcr.io/ianlewis-org/aggremod:0.9.1
          livenessProbe:
            # an http probe
            httpGet:
              path: /_status/healthz
              port: 8080
            # length of time to wait for a pod to initialize
            # after pod startup, before applying health checking
            initialDelaySeconds: 30
            timeoutSeconds: 1
          volumeMounts:
            - name: secret-volume
              mountPath: /secrets
            - name: certs
              mountPath: /etc/ssl/certs
              readOnly: true
          resources:
            limits:
              memory: 25Mi
              cpu: 25m
        - name: fluentd
          image: asia.gcr.io/ianlewis-org/aggremod-fluentd:0.12.29-1
          env:
            - name: GCP_SERVICE_ACCOUNT_KEY_PATH
              value: /secrets/service-account.json
            - name: GCP_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: aggremod-conf
                  key: project-id
            - name: GCP_BIGQUERY_DATASET
              valueFrom:
                configMapKeyRef:
                  name: aggremod-conf
                  key: bigquery-dataset
            - name: GCP_BIGQUERY_TABLE
              valueFrom:
                configMapKeyRef:
                  name: aggremod-conf
                  key: bigquery-table
          ports:
            - containerPort: 24224
          volumeMounts:
            - name: secret-volume
              mountPath: /secrets
            - name: fluentd-file-buffer
              mountPath: /var/log/fluent/
          resources:
            limits:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m
      volumes: 
        - name: certs
          hostPath:
            path: /etc/ssl/certs
        - name: secret-volume
          secret:
            secretName: aggremod-secret
        - name: fluentd-file-buffer
          gcePersistentDisk:
            # This GCE PD must already exist.
            pdName: aggremod-fluentd-buffer
            fsType: ext4
